name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.8.0

    - name: Docker Login 
      uses: docker/login-action@v3.3.0 
      with: 
        username: ${{ secrets.USERNAME_DOCKERHUB }}
        password: ${{ secrets.PASSWORD_DOCKERHUB }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.12.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: malkavz/go_ci:${{ github.ref_name }}
          
