name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.8.0

    - name: Docker Login 
      uses: docker/login-action@v2.0.0 
      with: 
        username: ${{ secrets.USERNAME_DOCKERHUB }}
        password: ${{ secrets.PASSWORD_DOCKERHUB }}
